### ISSUE TITLE
Surface/expose audit data around shipment changes / shipment triggers

### ISSUE THREAD

**Issue by mickeyyawn** [turnerlabs/harbor#28]
To avoid having to use a diff system to run compute, we need to expose who triggered what/when in Harbor.  This is for SOX compliance.

**Comment by jkurz** [comment]
So currently we store information about changes to shipit objects.
We have logs on when triggers were made, but we are not storing this information in a database.

We can easily expose shipit audit information in harbor today.
To expose triggers we can do a multitude of things. 
* use athena to query logs for when people triggered (we don't get who triggered)
* Authenticate trigger API and store in database
* Just have UIs send user information and not change trigger to be authenticated and store in database

The database solution could lean on shipit, since these apis are already tied together. 

We create a new model called `deployments`. A deployment is the combination of the shipit model, when it was triggered and by whom it was triggered. It could also have information in it, like successful, failed, and messages about why it failed.

**Comment by wilsonodk** [comment]
I like the DB solution, because we could then grab that data and display it to the clients.

**Comment by jkurz** [comment]
Another idea came up yesterday that could help implement this.

We could add webhooks to trigger. When a trigger is completed, it could send a webhook POST with information about that trigger. Who did it, what time it happened, how long it took, and the shipit model that was triggered. 

This could be used in many ways, but one way could be a service that stores the data back into the shipit database under a deployments table. Then we could query for what deployments were made and when. 

yes I understand getting the auth information still is not solved with this, but these are really two separate issues. One is get the data and one is notify when things changed. At the very least without user information on who triggered, it's still valuable to know when something was changed so we can debug based off of this data.

**Comment by mickeyyawn** [comment]
I like that additional feature Josh (webhook notification).  Gives the user the ability to hook up other notification systems if the want (email team members, slack room, etc...)

Or in the SOX arena, an email to ISO.  :-)

**Comment by jkurz** [comment]
This has been completed in shipit and trigger. 

https://github.com/turnerlabs/shipit-api/pull/28
https://bitbucket.org/vgtf/deployit-trigger/pull-requests/117/write-to-audit-trail-for-shipment-when/diff

**Comment by jkurz** [comment]
This has been surfaced in the UI here https://github.com/turnerlabs/harbor-ui/pull/35. Going to close this issue.
